import mongoose from 'mongoose';

const subtitleSchema = new mongoose.Schema({
  videoId: {
    type: String,
    required: true,
    index: true
  },
  roomCode: {
    type: String,
    required: true,
    index: true
  },
  language: {
    type: String,
    required: true,
    default: 'en'
  },
  format: {
    type: String,
    enum: ['vtt', 'srt'],
    default: 'vtt'
  },
  subtitles: [{
    startTime: {
      type: Number,
      required: true
    },
    endTime: {
      type: Number,
      required: true
    },
    text: {
      type: String,
      required: true
    },
    speaker: String
  }],
  transcript: {
    type: String,
    default: ''
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  accuracy: {
    type: Number,
    min: 0,
    max: 1,
    default: 1
  }
}, {
  timestamps: true
});

// Text search index for transcript
subtitleSchema.index({ transcript: 'text' });
subtitleSchema.index({ videoId: 1, roomCode: 1, language: 1 }, { unique: true });

export const Subtitle = mongoose.model('Subtitle', subtitleSchema);
